### ISSUE TITLE
Execution of the solver.py file.

### ISSUE THREAD

**Issue by jamigeo** [maybe-im-a-mess/Solver#1]
Hi 👋

I tried to run the solver.py file, however the solver function and the sat function are not recognized. How can I run this program?

And what input format does the execution need?

...

**Comment by maybe-im-a-mess** [comment]
Hello! 
Thank you for your question. 

The Solver and sat are probably not recognised, because you need z3-solver installed. Z3 is a theorem prover from Microsoft Research and those are internal functions of z3. 
To install it run `pip install z3-solver`. And then everything has to work. 

The format of input expression is a list of strings, e.g. `["x + y +z = 10", "x < y", "x < 3", "0 < x"]`. To run the code, you can just add one line in solver.py, e.g. `print(solve(["x + y +z = 10", "x < y", "x < 3", "0 < x"]))`.

If you have any further questions, feel free to ask!

**Comment by jamigeo** [comment]
Now it works! 
But apparently, the program cannot utilize any input format. Because I just tried: `print(solve(["x + y - z = 15", "x > y", "x < 5", "0 < x"]))` This raises a Z3Exception: ` raise Z3Exception(msg)
z3.z3types.Z3Exception: Value cannot be converted into a Z3 Boolean value`...

**Comment by maybe-im-a-mess** [comment]
Correct, in your equation you are using ">" sign. The solver only works with "less than" and"equal", as stated in the boolean grammar for the task: 
```
The grammar of boolean expressions is:
<boolean_expression> ::= <disjunct> ’or’ <boolean_expression> | <disjunct>
<disjunct> ::= <conjunct> ’and’ <disjunct> | <conjunct>
<conjunct> ::= <arithmetic_expression> <cmp> <arithmetic_expression>
| (<boolean_expression>)
<cmp> ::= ’=’ | ’<’
```
